config/routes.rb
Rails.application.routes.draw do
  resources :scores, only: [:new, :index] do
    collection { post :import }
  end

  root 'scores#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/score.rb
require "csv"

class Score < ApplicationRecord
  validates :user_name, :score_number, :date, :user_id, presence: true

  validates_numericality_of :score_number, less_than: 3126

  # Import a file and parses into the database
  # Should be a .csv file
  # See pontuacao1.csv for example
  # @return nil
  def self.import(file)
    CSV.foreach(file.path, col_sep: ";") do |row|
      Score.create date: row[0], user_name: row[1], user_id: row[2], score_number: row[3]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  def new; end

  def index
    @scores = Score.order(score_number: :desc)
  end

  def import
    @score_importer = Score.import(params[:file])
    redirect_to scores_path, notice: "Importado com sucesso."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def translate_attribute(model, attribute, count = 1)
    model.human_attribute_name attribute, count: count
  end

  alias ta translate_attribute
end

app/helpers/navbar_helper.rb
module NavbarHelper
  # Example:
  #
  #     <%= navbar_link_to(
  #           "Home",
  #           root_path,
  #           active_when: { controller: "home" }) %>
  #
  def navbar_link_to(label, path, options={})
    active_when = options.delete(:active_when) { {} }
    active = active_when.all? do |key, value|
      case value
      when Regexp
        params[key].to_s =~ value
      else
        params[key].to_s == value
      end
    end

    content_tag(:li, class: ("active" if active)) do
      link_to(label, path, options)
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Desafio <%= Rails.application.config.version %> (<%= l(Rails.application.config.version_time) %>) -->

    <%# CSS should go closest to the top of the document as possible. %>
    <%= stylesheet_link_tag("application",
                            media: "all",
                            "data-turbolinks-track" => "reload") %>

    <%# JavaScript must be in head for Turbolinks to work. %>
    <%= javascript_include_tag("application",
                                     "data-turbolinks-track" => "reload") %>

    <%= yield(:head) %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%# Specifies the default name of home screen bookmark in iOS 6+ %>
    <meta name="apple-mobile-web-app-title" content="Desafio">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <title>
      <%= strip_tags(yield(:title)) + " – " if content_for?(:title) %>
      Desafio
    </title>
  </head>
  <body>

	<%= render("shared/navbar") %>

	<div class="container">

	  <%= render("shared/flash") %>

	  <%= yield %>

	  <%= render("shared/footer") %>
	</div>
  </body>
</html>

app/views/scores/index.html.erb
<h1>Pontuação de usuários</h1>

  <table class="table table-hover">
    <thead>
      <tr>
        <th class="text-center"><%= ta Score, :user_id %></th>
        <th class="text-center"><%= ta Score, :user_name %></th>
        <th class="text-center"><%= ta Score, :score_number %></th>
        <th class="text-center"><%= ta Score, :date %></th>
      </tr>
    </thead>
    <tbody>
    <% @scores.each do |score| %>
      <tr>
        <td class="text-center"><%= score.user_id %></td>
        <td class="text-center"><%= score.user_name %></td>
        <td class="text-center"><%= score.score_number %></td>
        <td class="text-center"><%= l score.date %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<div class="col-sm-12" style="margin-top: 10px;">
  <%= link_to 'Importar nova tabela de Pontuação', new_score_path, class:"btn btn-primary pull-right" %>
</div>

app/views/scores/new.html.erb
<div class="page-header">
  <h1>Importar nova tabela de pontuação</h1>
</div>

<%= form_tag import_scores_path, multipart: true, class: 'form-inline file-csv' do%>
  <%= file_field_tag :file, class: 'form-control', required: true %>
  <%= submit_tag 'Importar CSV', onclick: "return validateFileFormat();", class: 'btn btn-primary' %>
<% end %>

app/views/shared/_flash.html.erb
<%# Notice %>
<% if flash[:notice].present? %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<%# Alert %>
<% if flash[:alert].present? %>
  <div class="alert alert-danger"><%= flash[:alert] %></div>
<% end %>

app/views/shared/_footer.html.erb
<hr>

<footer>
  <p>© Desafio <%= Time.zone.now.strftime("%Y") %></p>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to("Desafio", root_path, class: "navbar-brand") %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <%= navbar_link_to("Home", root_path, active_when: { controller: "scores" }) %>
    </div><!--/.nav-collapse -->
  </div>
</div>